//! Shared helpers and macros used across the learner/explain modules.
//!
//! Macros here (`define_learner!`, `add_explain_methods!`, `declare_support!`)
//! are meant to be invoked from the SAME file that defines the target
//! `#[pyclass]` struct -- macro-expanded code's module (for field-privacy
//! purposes) is the invocation site, so e.g. `self.trained` in a method
//! generated by `add_explain_methods!` only compiles if the struct's private
//! `trained` field was declared in that same invoking file.

use ndarray::Array2;
use numpy::{PyArray1, PyArray2, PyReadonlyArray2};
use pyo3::exceptions::PyRuntimeError;
use pyo3::prelude::*;
use smelt_ml::learner::{Learner, TrainedModel};
use smelt_ml::measure::Measure;
use smelt_ml::prediction::Prediction;

pub(crate) fn to_array2(x: PyReadonlyArray2<'_, f64>) -> Array2<f64> {
    x.as_array().to_owned()
}

/// Maps a core `SmeltError` to a Python exception. Bad-input variants (an
/// out-of-range/inconsistent hyperparameter, or mismatched array lengths --
/// exactly what `Vec<i64>`/labels validation elsewhere in this crate already
/// raises `ValueError` for) become `ValueError`, matching Python convention
/// and the errors' own semantics; everything else (internal/numerical
/// failures, I/O, not-yet-fitted) stays `RuntimeError` as before. Before
/// this, every `SmeltError` -- including the now-typed `InvalidParameter`/
/// `DimensionMismatch` the core added in Fase C of the 2026-07-04 audit --
/// mapped to the same `RuntimeError` regardless of whether it was a usage
/// mistake a caller should `except ValueError` for.
pub(crate) fn smelt_err(e: smelt_ml::SmeltError) -> PyErr {
    use smelt_ml::SmeltError;
    match &e {
        SmeltError::InvalidParameter(_) | SmeltError::DimensionMismatch { .. } => {
            pyo3::exceptions::PyValueError::new_err(format!("{e}"))
        }
        _ => PyRuntimeError::new_err(format!("{e}")),
    }
}

pub(crate) fn is_integer(y: &Bound<'_, PyAny>) -> bool {
    if let Ok(arr) = y.getattr("dtype") {
        if let Ok(kind) = arr.getattr("kind") {
            if let Ok(k) = kind.extract::<String>() {
                return k == "i" || k == "u" || k == "b";
            }
        }
    }
    y.extract::<Vec<i64>>().is_ok()
}

/// Convert Python integer labels to non-negative `usize` class indices.
/// Rejects negative labels explicitly instead of letting `v as usize` wrap
/// (e.g. the SVM convention `y = [-1, 1]` would otherwise become
/// `18446744073709551615`, silently corrupting the class count downstream).
pub(crate) fn extract_class_labels(y: &Bound<'_, PyAny>) -> PyResult<Vec<usize>> {
    let target: Vec<i64> = y.extract()?;
    target
        .into_iter()
        .enumerate()
        .map(|(i, v)| {
            usize::try_from(v).map_err(|_| {
                pyo3::exceptions::PyValueError::new_err(format!(
                    "negative class label {v} at index {i}; class labels must be non-negative integers"
                ))
            })
        })
        .collect()
}

/// Convert Python integer treatment-arm labels (0=control, 1=treated, ...)
/// to non-negative `usize` arm indices, for the causal meta-learners
/// (`causal.rs`). Those `estimate()` methods used to declare `treatment:
/// Vec<usize>` directly in the `#[pymethods]` signature, so PyO3 extracted
/// it into `Vec<usize>` *before the function body ran* -- a negative
/// treatment value (an easy typo, e.g. the SVM-style `-1` convention)
/// raised an opaque `OverflowError: can't convert negative int to
/// unsigned` with no mention of which argument or index was at fault.
/// Declaring the parameter as `Vec<i64>` instead and validating explicitly
/// here gives a clear `ValueError` naming the actual problem, matching
/// [`extract_class_labels`]'s existing convention.
pub(crate) fn extract_treatment_labels(treatment: Vec<i64>) -> PyResult<Vec<usize>> {
    treatment
        .into_iter()
        .enumerate()
        .map(|(i, v)| {
            usize::try_from(v).map_err(|_| {
                pyo3::exceptions::PyValueError::new_err(format!(
                    "negative treatment arm {v} at index {i}; treatment must be encoded as \
                     non-negative integers (0=control, 1=treated, ...)"
                ))
            })
        })
        .collect()
}

/// Train a learner, releasing the GIL for the (rayon-parallel, potentially
/// long-running) training call. `y` is extracted into an owned Rust value
/// first since that requires the GIL; the actual `train_classif`/
/// `train_regress` call runs under `py.allow_threads` so it doesn't block
/// other Python threads (e.g. a Jupyter kernel) or Ctrl+C for the duration.
pub(crate) fn fit_learner(
    py: Python<'_>,
    learner: &mut dyn Learner,
    features: Array2<f64>,
    y: &Bound<'_, PyAny>,
) -> PyResult<(Box<dyn TrainedModel>, bool)> {
    fit_learner_cat(py, learner, features, y, None)
}

/// Like `fit_learner`, but declares `cat_features` (column indices) as
/// categorical on the `Task` before training -- this is how XGBoost/LightGBM/
/// CatBoost's native categorical splits (item 14c) learn about categorical
/// columns from Python, since the `fit(x, y)` entry point only sees raw
/// ndarrays and has no other place to carry that metadata.
pub(crate) fn fit_learner_cat(
    py: Python<'_>,
    learner: &mut dyn Learner,
    features: Array2<f64>,
    y: &Bound<'_, PyAny>,
    cat_features: Option<Vec<usize>>,
) -> PyResult<(Box<dyn TrainedModel>, bool)> {
    if is_integer(y) {
        let target = extract_class_labels(y)?;
        let mut task = smelt_ml::task::ClassificationTask::new("py", features, target)
            .map_err(smelt_err)?;
        if let Some(cats) = cat_features {
            task = task.with_categorical_features(&cats).map_err(smelt_err)?;
        }
        let model = py
            .allow_threads(|| learner.train_classif(&task))
            .map_err(smelt_err)?;
        Ok((model, true))
    } else {
        let target: Vec<f64> = y.extract()?;
        let mut task =
            smelt_ml::task::RegressionTask::new("py", features, target).map_err(smelt_err)?;
        if let Some(cats) = cat_features {
            task = task.with_categorical_features(&cats).map_err(smelt_err)?;
        }
        let model = py
            .allow_threads(|| learner.train_regress(&task))
            .map_err(smelt_err)?;
        Ok((model, false))
    }
}

/// Build the `EvalSet`-shaped pair from a Python `(x_val, y_val)` tuple for
/// the eval-set builders (`with_eval_set_regress`/`with_eval_set_classif`,
/// item 14b). Classification vs regression is decided the same way as the
/// main training target (`is_integer`), so an eval set must agree in kind
/// with `y` -- passing a float eval target against an integer `y` (or vice
/// versa) is rejected by the learner's own `train_*` at fit time.
pub(crate) fn parse_eval_set(
    eval_set: Option<(PyReadonlyArray2<'_, f64>, Bound<'_, PyAny>)>,
) -> PyResult<Option<(Array2<f64>, EvalKind)>> {
    match eval_set {
        None => Ok(None),
        Some((x, y)) => {
            let features = to_array2(x);
            if is_integer(&y) {
                Ok(Some((features, EvalKind::Classification(extract_class_labels(&y)?))))
            } else {
                Ok(Some((features, EvalKind::Regression(y.extract()?))))
            }
        }
    }
}

/// Classification/regression eval-set target, returned by `parse_eval_set`.
pub(crate) enum EvalKind {
    Classification(Vec<usize>),
    Regression(Vec<f64>),
}

pub(crate) fn predict_values<'py>(
    model: &dyn TrainedModel,
    py: Python<'py>,
    x: PyReadonlyArray2<'_, f64>,
) -> PyResult<Bound<'py, PyArray1<f64>>> {
    let features = to_array2(x);
    let pred = py.allow_threads(|| model.predict(&features)).map_err(smelt_err)?;
    let values: Vec<f64> = match &pred {
        Prediction::Classification { predicted, .. } => {
            predicted.iter().map(|&p| p as f64).collect()
        }
        Prediction::Regression { predicted, .. } => predicted.clone(),
        Prediction::CausalEffect { estimated, .. } => estimated.clone(),
    };
    Ok(PyArray1::from_vec(py, values))
}

pub(crate) fn predict_proba_values<'py>(
    model: &dyn TrainedModel,
    py: Python<'py>,
    x: PyReadonlyArray2<'_, f64>,
) -> PyResult<Bound<'py, PyArray2<f64>>> {
    let features = to_array2(x);
    let pred = py.allow_threads(|| model.predict(&features)).map_err(smelt_err)?;
    match &pred {
        Prediction::Classification {
            probabilities: Some(probs),
            ..
        } => {
            let n = probs.len();
            let k = probs.first().map_or(0, |row| row.len());
            let flat: Vec<f64> = probs.iter().flatten().copied().collect();
            let arr = Array2::from_shape_vec((n, k), flat)
                .map_err(|e| PyRuntimeError::new_err(e.to_string()))?;
            Ok(PyArray2::from_owned_array(py, arr))
        }
        _ => Err(PyRuntimeError::new_err("No probabilities available")),
    }
}

pub(crate) fn not_fitted() -> PyErr {
    PyRuntimeError::new_err("Model not fitted. Call fit() first.")
}

/// Save a fitted model to a JSON file. Fails with a clear error for
/// composite learners that hold other trained models internally (Bagging,
/// Stacking, DynamicEnsemble, CostSensitiveClassifier, GeoXGBoost,
/// KrigingHybrid, DeepForest) -- `SerializableModel` has no variant for
/// those, so `to_serializable` returns `None`.
pub(crate) fn save_model(trained: &Option<Box<dyn TrainedModel>>, path: &str) -> PyResult<()> {
    let model = trained.as_deref().ok_or_else(not_fitted)?;
    let serializable = model.to_serializable().ok_or_else(|| {
        PyRuntimeError::new_err(
            "this model type does not support serialization: it holds other trained \
             models internally, and smelt_ml::serialize::SerializableModel has no \
             variant for it",
        )
    })?;
    smelt_ml::serialize::save_json(&serializable, path).map_err(smelt_err)
}

/// Load a model from a JSON file, checking its `model_type` tag against
/// `expected` so e.g. `RandomForest.load("catboost_model.json")` fails
/// clearly instead of silently wrapping the wrong learner's predictions
/// under the `RandomForest` class name.
pub(crate) fn load_model_checked(path: &str, expected: &str) -> PyResult<Box<dyn TrainedModel>> {
    let serializable = smelt_ml::serialize::load_json(path).map_err(smelt_err)?;
    let actual = serializable.type_name();
    if actual != expected {
        return Err(pyo3::exceptions::PyValueError::new_err(format!(
            "expected a '{expected}' model in {path}, found '{actual}'"
        )));
    }
    Ok(Box::new(serializable))
}

/// Parse coords from numpy array (Nx2), list of tuples, or list of lists.
pub(crate) fn parse_coords(coords: &Bound<'_, PyAny>) -> PyResult<Vec<(f64, f64)>> {
    let parsed = parse_coords_unchecked(coords)?;
    for (i, &(x, y)) in parsed.iter().enumerate() {
        if !x.is_finite() || !y.is_finite() {
            return Err(PyRuntimeError::new_err(format!(
                "coords[{i}] = ({x}, {y}) must be finite (no NaN/inf) — \
                 non-finite coordinates silently corrupt spatial distance calculations"
            )));
        }
    }
    Ok(parsed)
}

fn parse_coords_unchecked(coords: &Bound<'_, PyAny>) -> PyResult<Vec<(f64, f64)>> {
    // Try numpy 2D array first (most common case)
    if let Ok(arr) = coords.extract::<PyReadonlyArray2<'_, f64>>() {
        let a = arr.as_array();
        if a.ncols() != 2 {
            return Err(PyRuntimeError::new_err(format!(
                "coords array must have 2 columns (X, Y), got {}",
                a.ncols()
            )));
        }
        return Ok(a.rows().into_iter().map(|r| (r[0], r[1])).collect());
    }
    // Fallback: list of (x, y) tuples
    if let Ok(tuples) = coords.extract::<Vec<(f64, f64)>>() {
        return Ok(tuples);
    }
    // Fallback: list of [x, y] lists
    if let Ok(lists) = coords.extract::<Vec<Vec<f64>>>() {
        let mut out = Vec::with_capacity(lists.len());
        for (i, v) in lists.iter().enumerate() {
            if v.len() != 2 {
                return Err(PyRuntimeError::new_err(format!(
                    "coords[{i}] must have 2 elements, got {}",
                    v.len()
                )));
            }
            out.push((v[0], v[1]));
        }
        return Ok(out);
    }
    Err(PyRuntimeError::new_err(
        "coords must be a numpy array (Nx2), list of (x, y) tuples, or list of [x, y] lists",
    ))
}

pub(crate) fn resolve_measure(metric: &str) -> PyResult<Box<dyn Measure>> {
    use smelt_ml::measure::*;
    match metric {
        "rmse" => Ok(Box::new(Rmse)),
        "mae" => Ok(Box::new(Mae)),
        "r2" => Ok(Box::new(RSquared)),
        "mape" => Ok(Box::new(Mape)),
        "accuracy" => Ok(Box::new(Accuracy)),
        "f1" => Ok(Box::new(F1Score)),
        "precision" => Ok(Box::new(Precision)),
        "recall" => Ok(Box::new(Recall)),
        "logloss" => Ok(Box::new(LogLoss)),
        "auc" => Ok(Box::new(AucRoc)),
        // Added alongside balanced_accuracy_score/kappa_score/mcc_score/
        // brier_score (measures.rs): those functions existed, but the
        // measures usable *by name* here (e.g. `BayesianOptimizer.optimize`,
        // `permutation_importance`) didn't include them.
        "balanced_accuracy" => Ok(Box::new(BalancedAccuracy)),
        "kappa" => Ok(Box::new(CohensKappa)),
        "mcc" => Ok(Box::new(Mcc)),
        "brier" => Ok(Box::new(Brier)),
        _ => Err(PyRuntimeError::new_err(format!("Unknown metric: {metric}"))),
    }
}

pub(crate) fn shap_impl<'py>(
    py: Python<'py>,
    model: &dyn TrainedModel,
    is_classif: bool,
    x: PyReadonlyArray2<'_, f64>,
    y: &Bound<'_, PyAny>,
    n_background: usize,
    feature_names: Option<Vec<String>>,
    target_class: usize,
) -> PyResult<PyObject> {
    let features = to_array2(x);
    let n_feat = features.ncols();
    let names = feature_names.unwrap_or_else(|| (0..n_feat).map(|i| format!("f{i}")).collect());

    let result = if is_classif {
        let target = extract_class_labels(y)?;
        let mut task = smelt_ml::task::ClassificationTask::new("shap", features, target)
            .map_err(smelt_err)?;
        task = task.with_feature_names(names.clone()).map_err(smelt_err)?;
        py.allow_threads(|| {
            smelt_ml::importance::shap::tree_shap_classif(model, &task, n_background, target_class)
        })
        .map_err(smelt_err)?
    } else {
        let target: Vec<f64> = y.extract()?;
        let mut task = smelt_ml::task::RegressionTask::new("shap", features, target)
            .map_err(smelt_err)?;
        task = task.with_feature_names(names.clone()).map_err(smelt_err)?;
        py.allow_threads(|| smelt_ml::importance::shap::tree_shap_regress(model, &task, n_background))
            .map_err(smelt_err)?
    };

    // Convert to Python dict
    let dict = pyo3::types::PyDict::new(py);

    // SHAP values as 2D numpy array
    let n = result.explanations.len();
    let p = if n > 0 { result.explanations[0].values.len() } else { 0 };
    let flat: Vec<f64> = result.explanations.iter()
        .flat_map(|e| e.values.iter().copied()).collect();
    let arr = ndarray::Array2::from_shape_vec((n, p), flat)
        .map_err(|e| PyRuntimeError::new_err(e.to_string()))?;
    dict.set_item("values", PyArray2::from_owned_array(py, arr))?;

    dict.set_item("base_value",
        result.explanations.first().map(|e| e.base_value).unwrap_or(0.0))?;
    dict.set_item("feature_names", &names)?;

    let imp: Vec<(String, f64)> = result.global_importance;
    dict.set_item("global_importance", imp)?;

    Ok(dict.into_pyobject(py)?.into_any().unbind())
}

pub(crate) fn perm_importance_impl<'py>(
    py: Python<'py>,
    model: &dyn TrainedModel,
    is_classif: bool,
    x: PyReadonlyArray2<'_, f64>,
    y: &Bound<'_, PyAny>,
    metric: &str,
    n_repeats: usize,
    seed: u64,
    feature_names: Option<Vec<String>>,
) -> PyResult<PyObject> {
    let features = to_array2(x);
    let n_feat = features.ncols();
    let names = feature_names.unwrap_or_else(|| (0..n_feat).map(|i| format!("f{i}")).collect());
    let measure = resolve_measure(metric)?;

    let importances = if is_classif {
        let target = extract_class_labels(y)?;
        let mut task = smelt_ml::task::ClassificationTask::new("perm", features, target)
            .map_err(smelt_err)?;
        task = task.with_feature_names(names).map_err(smelt_err)?;
        py.allow_threads(|| {
            smelt_ml::importance::permutation_importance_classif(
                model, &task, &*measure, n_repeats, seed,
            )
        })
        .map_err(smelt_err)?
    } else {
        let target: Vec<f64> = y.extract()?;
        let mut task = smelt_ml::task::RegressionTask::new("perm", features, target)
            .map_err(smelt_err)?;
        task = task.with_feature_names(names).map_err(smelt_err)?;
        py.allow_threads(|| {
            smelt_ml::importance::permutation_importance_regress(
                model, &task, &*measure, n_repeats, seed,
            )
        })
        .map_err(smelt_err)?
    };

    // Return list of dicts
    let list = pyo3::types::PyList::empty(py);
    for fi in &importances {
        let d = pyo3::types::PyDict::new(py);
        d.set_item("feature", &fi.feature)?;
        d.set_item("importance", fi.importance)?;
        d.set_item("std_dev", fi.std_dev)?;
        list.append(d)?;
    }
    Ok(list.into_pyobject(py)?.into_any().unbind())
}

pub(crate) fn conformal_predict_impl<'py>(
    py: Python<'py>,
    model: &dyn TrainedModel,
    x_cal: PyReadonlyArray2<'_, f64>,
    y_cal: Vec<f64>,
    x_test: PyReadonlyArray2<'_, f64>,
    alpha: f64,
) -> PyResult<PyObject> {
    let cal_features = to_array2(x_cal);
    let test_features = to_array2(x_test);

    let (intervals, interval_width) = py
        .allow_threads(|| {
            let cf = smelt_ml::conformal::ConformalRegressor::calibrate(
                model, &cal_features, &y_cal, alpha,
            )?;
            let intervals = cf.predict(&test_features)?;
            Ok::<_, smelt_ml::SmeltError>((intervals, cf.interval_width()))
        })
        .map_err(smelt_err)?;

    let n = intervals.len();
    let mut preds = Vec::with_capacity(n);
    let mut lower = Vec::with_capacity(n);
    let mut upper = Vec::with_capacity(n);
    for iv in &intervals {
        preds.push(iv.prediction);
        lower.push(iv.lower);
        upper.push(iv.upper);
    }

    let dict = pyo3::types::PyDict::new(py);
    dict.set_item("predictions", PyArray1::from_vec(py, preds))?;
    dict.set_item("lower", PyArray1::from_vec(py, lower))?;
    dict.set_item("upper", PyArray1::from_vec(py, upper))?;
    dict.set_item("interval_width", interval_width)?;
    dict.set_item("alpha", alpha)?;
    Ok(dict.into_pyobject(py)?.into_any().unbind())
}

/// Defines a PyO3 wrapper class for a smelt-ml learner: the `#[pyclass]`
/// struct holding hyperparameters + trained state, `new`/`fit`/`predict`,
/// a `feature_importances_` getter (always safe -- `Learner::feature_importance`
/// defaults to `None` for learners that don't implement it), and optionally
/// `predict_proba` for classification-capable learners. Exposes a reasonable
/// subset of each learner's hyperparameters, matching the hand-written
/// wrappers (e.g. `RandomForest` doesn't expose `subsample`/
/// `colsample_bytree` either) rather than the full Rust builder surface.
///
/// Invoke this in the same file you want the generated struct to live in.
///
/// An optional trailing `note = "..."` becomes the class's Python
/// docstring (`#[doc = ...]` on the generated `#[pyclass]` struct, which
/// PyO3 surfaces as `__doc__`) -- use it for caveats a user would only
/// otherwise discover by reading the Rust source, e.g. a streaming
/// learner's batch-mode hyperparameter defaults not suiting small batches.
macro_rules! define_learner {
    (
        name = $name:ident,
        params = { $( $field:ident : $ty:ty = $default:expr ),* $(,)? },
        ctor = |$slf:ident| $ctor_expr:expr,
        proba = $has_proba:tt,
        serial_as = $serial_as:literal
        $(, note = $note:literal)? $(,)?
    ) => {
        $( #[doc = $note] )?
        #[pyo3::pyclass]
        #[derive(Default)]
        pub(crate) struct $name {
            trained: Option<Box<dyn smelt_ml::learner::TrainedModel>>,
            is_classif: bool,
            $( $field: $ty, )*
        }

        #[pyo3::pymethods]
        impl $name {
            #[new]
            #[pyo3(signature = ( $( $field = $default ),* ))]
            fn new( $( $field: $ty ),* ) -> Self {
                Self { trained: None, is_classif: false, $( $field ),* }
            }

            fn fit(
                &mut self,
                py: pyo3::Python<'_>,
                x: numpy::PyReadonlyArray2<'_, f64>,
                y: &pyo3::Bound<'_, pyo3::PyAny>,
            ) -> pyo3::PyResult<()> {
                let mut learner = { let $slf = &*self; $ctor_expr };
                let (model, is_classif) = crate::common::fit_learner(py, &mut learner, crate::common::to_array2(x), y)?;
                self.trained = Some(model);
                self.is_classif = is_classif;
                Ok(())
            }

            fn predict<'py>(
                &self,
                py: pyo3::Python<'py>,
                x: numpy::PyReadonlyArray2<'_, f64>,
            ) -> pyo3::PyResult<pyo3::Bound<'py, numpy::PyArray1<f64>>> {
                crate::common::predict_values(self.trained.as_deref().ok_or_else(crate::common::not_fitted)?, py, x)
            }

            #[getter]
            fn feature_importances_(&self) -> pyo3::PyResult<Option<Vec<(String, f64)>>> {
                Ok(self.trained.as_ref().ok_or_else(crate::common::not_fitted)?.feature_importance())
            }

            /// Return constructor hyperparameters as a dict (sklearn-style `get_params`).
            fn get_params(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
                let dict = pyo3::types::PyDict::new(py);
                $( dict.set_item(stringify!($field), self.$field.clone())?; )*
                Ok(dict.into_pyobject(py)?.into_any().unbind())
            }

            /// Update hyperparameters in place (sklearn-style `set_params`); unknown
            /// keys raise `ValueError`. Does not affect an already-fitted model.
            #[pyo3(signature = (**kwargs))]
            fn set_params(&mut self, kwargs: Option<&pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<()> {
                if let Some(kwargs) = kwargs {
                    for (k, v) in kwargs.iter() {
                        let key: String = k.extract()?;
                        $(
                            if key == stringify!($field) {
                                self.$field = v.extract()?;
                                continue;
                            }
                        )*
                        return Err(pyo3::exceptions::PyValueError::new_err(format!(
                            "invalid parameter '{key}' for this estimator"
                        )));
                    }
                }
                Ok(())
            }

            /// Save the fitted model to a JSON file.
            fn save(&self, path: &str) -> pyo3::PyResult<()> {
                crate::common::save_model(&self.trained, path)
            }

            /// Load a previously saved model from a JSON file. `is_classif` must
            /// match how the model was originally trained -- the saved file
            /// carries no such flag of its own. Hyperparameters reset to the
            /// CONSTRUCTOR defaults (the file doesn't store them): a refit
            /// behaves like a fresh default-constructed learner, not like the
            /// (unknown) original configuration -- call `set_params` first to
            /// restore yours.
            #[staticmethod]
            #[pyo3(signature = (path, is_classif=false))]
            fn load(path: &str, is_classif: bool) -> pyo3::PyResult<Self> {
                // Constructor defaults, NOT Default::default(): the derived
                // Default zeroes every field, so a refit after load trained
                // silently with e.g. n_estimators=0 (audit M-16).
                let mut inst = Self::new( $( $default ),* );
                inst.trained = Some(crate::common::load_model_checked(path, $serial_as)?);
                inst.is_classif = is_classif;
                Ok(inst)
            }
        }

        crate::common::define_learner!(@proba $name, $has_proba);
    };
    (@proba $name:ident, true) => {
        #[pyo3::pymethods]
        impl $name {
            fn predict_proba<'py>(
                &self,
                py: pyo3::Python<'py>,
                x: numpy::PyReadonlyArray2<'_, f64>,
            ) -> pyo3::PyResult<pyo3::Bound<'py, numpy::PyArray2<f64>>> {
                crate::common::predict_proba_values(self.trained.as_deref().ok_or_else(crate::common::not_fitted)?, py, x)
            }
        }
    };
    (@proba $name:ident, false) => {};
}
pub(crate) use define_learner;

/// Adds `shap_values`, `permutation_importance`, and `conformal_predict` to a
/// learner wrapper struct that has `trained: Option<Box<dyn TrainedModel>>`
/// and `is_classif: bool` fields. Invoke this in the same file that defines
/// the struct.
macro_rules! add_explain_methods {
    ($($name:ident),+ $(,)?) => {
        $(
            #[pyo3::pymethods]
            impl $name {
                /// Compute SHAP values for each sample.
                #[pyo3(signature = (x, y, n_background=50, feature_names=None, target_class=1))]
                fn shap_values<'py>(
                    &self,
                    py: pyo3::Python<'py>,
                    x: numpy::PyReadonlyArray2<'_, f64>,
                    y: &pyo3::Bound<'_, pyo3::PyAny>,
                    n_background: usize,
                    feature_names: Option<Vec<String>>,
                    target_class: usize,
                ) -> pyo3::PyResult<pyo3::PyObject> {
                    let model = self.trained.as_deref().ok_or_else(crate::common::not_fitted)?;
                    crate::common::shap_impl(py, model, self.is_classif, x, y, n_background, feature_names, target_class)
                }

                /// Compute permutation importance.
                #[pyo3(signature = (x, y, metric="rmse", n_repeats=5, seed=42, feature_names=None))]
                fn permutation_importance<'py>(
                    &self,
                    py: pyo3::Python<'py>,
                    x: numpy::PyReadonlyArray2<'_, f64>,
                    y: &pyo3::Bound<'_, pyo3::PyAny>,
                    metric: &str,
                    n_repeats: usize,
                    seed: u64,
                    feature_names: Option<Vec<String>>,
                ) -> pyo3::PyResult<pyo3::PyObject> {
                    let model = self.trained.as_deref().ok_or_else(crate::common::not_fitted)?;
                    crate::common::perm_importance_impl(py, model, self.is_classif, x, y, metric, n_repeats, seed, feature_names)
                }

                /// Split conformal prediction intervals with guaranteed (1-alpha) coverage.
                ///
                /// Args:
                ///     x_cal, y_cal: calibration data (held out from training)
                ///     x_test: features to predict on
                ///     alpha: miscoverage level (default 0.1 → 90% coverage)
                ///
                /// Returns dict with: "predictions", "lower", "upper" (numpy arrays),
                /// "interval_width" (float), "alpha" (float).
                #[pyo3(signature = (x_cal, y_cal, x_test, alpha=0.1))]
                fn conformal_predict<'py>(
                    &self,
                    py: pyo3::Python<'py>,
                    x_cal: numpy::PyReadonlyArray2<'_, f64>,
                    y_cal: Vec<f64>,
                    x_test: numpy::PyReadonlyArray2<'_, f64>,
                    alpha: f64,
                ) -> pyo3::PyResult<pyo3::PyObject> {
                    let model = self.trained.as_deref().ok_or_else(crate::common::not_fitted)?;
                    if self.is_classif {
                        return Err(pyo3::exceptions::PyRuntimeError::new_err(
                            "conformal_predict is only available for regression models",
                        ));
                    }
                    crate::common::conformal_predict_impl(py, model, x_cal, y_cal, x_test, alpha)
                }
            }
        )+
    };
}
pub(crate) use add_explain_methods;

/// Declares `supports_classification`/`supports_regression` getters for a
/// learner wrapper struct. Invoke this in the same file that defines the
/// struct.
macro_rules! declare_support {
    ($name:ident, classif = $c:expr, regress = $r:expr) => {
        #[pyo3::pymethods]
        impl $name {
            /// Whether this learner can train on classification targets (integer y).
            #[getter]
            fn supports_classification(&self) -> bool { $c }

            /// Whether this learner can train on regression targets (continuous y).
            #[getter]
            fn supports_regression(&self) -> bool { $r }
        }
    };
}
pub(crate) use declare_support;

/// Declares sklearn-style `get_params`/`set_params` for a hand-written learner
/// wrapper struct (one that doesn't go through `define_learner!`). Each
/// `field => "pyname"` pair maps a Rust field to its Python-facing parameter
/// name -- usually identical, but they differ where the constructor renames a
/// field to dodge a Python keyword (e.g. `lambda` -> `lambda_`). Invoke this
/// in the same file that defines the struct.
macro_rules! declare_params {
    ($name:ident, { $( $field:ident => $pyname:literal ),* $(,)? }) => {
        #[pyo3::pymethods]
        impl $name {
            /// Return constructor hyperparameters as a dict (sklearn-style `get_params`).
            fn get_params(&self, py: pyo3::Python<'_>) -> pyo3::PyResult<pyo3::PyObject> {
                let dict = pyo3::types::PyDict::new(py);
                $( dict.set_item($pyname, self.$field.clone())?; )*
                Ok(dict.into_pyobject(py)?.into_any().unbind())
            }

            /// Update hyperparameters in place (sklearn-style `set_params`); unknown
            /// keys raise `ValueError`. Does not affect an already-fitted model.
            #[pyo3(signature = (**kwargs))]
            #[allow(unused_variables)]
            fn set_params(&mut self, kwargs: Option<&pyo3::Bound<'_, pyo3::types::PyDict>>) -> pyo3::PyResult<()> {
                if let Some(kwargs) = kwargs {
                    for (k, v) in kwargs.iter() {
                        let key: String = k.extract()?;
                        match key.as_str() {
                            $( $pyname => { self.$field = v.extract()?; } )*
                            other => return Err(pyo3::exceptions::PyValueError::new_err(format!(
                                "invalid parameter '{other}' for this estimator"
                            ))),
                        }
                    }
                }
                Ok(())
            }
        }
    };
}
pub(crate) use declare_params;

/// Declares `save`/`load` for a hand-written learner wrapper struct (one
/// that doesn't go through `define_learner!`). `$name` must implement
/// `Default` (for `load`'s placeholder hyperparameters) and have `trained:
/// Option<Box<dyn TrainedModel>>` / `is_classif: bool` fields. `$serial_as`
/// is the expected `SerializableModel::type_name()` for this learner --
/// checked on load so e.g. loading a CatBoost file into `RandomForest`
/// fails clearly instead of silently predicting with the wrong model.
/// Invoke this in the same file that defines the struct.
macro_rules! add_persistence_methods {
    ($($name:ident => $serial_as:literal),+ $(,)?) => {
        $(
            #[pyo3::pymethods]
            impl $name {
                /// Save the fitted model to a JSON file.
                fn save(&self, path: &str) -> pyo3::PyResult<()> {
                    crate::common::save_model(&self.trained, path)
                }

                /// Load a previously saved model from a JSON file. `is_classif`
                /// must match how the model was originally trained -- the saved
                /// file carries no such flag of its own. Hyperparameters reset
                /// to the CONSTRUCTOR defaults (the file doesn't store them): a
                /// refit behaves like a fresh default-constructed learner, not
                /// like the (unknown) original configuration -- call
                /// `set_params` first to restore yours.
                #[staticmethod]
                #[pyo3(signature = (path, is_classif=false))]
                fn load(
                    py: pyo3::Python<'_>,
                    path: &str,
                    is_classif: bool,
                ) -> pyo3::PyResult<pyo3::Py<Self>> {
                    // Validate the file first so a type mismatch keeps its
                    // clear error, then build the instance through the
                    // PYTHON constructor: `Default::default()` zeroes every
                    // field, so a refit after load trained silently with
                    // e.g. n_estimators=0 or failed on objective ""
                    // (audit M-16). call0() applies the real signature
                    // defaults instead.
                    let model = crate::common::load_model_checked(path, $serial_as)?;
                    let obj = py.get_type::<Self>().call0()?;
                    {
                        let bound = obj.downcast::<Self>().map_err(|e| {
                            pyo3::exceptions::PyRuntimeError::new_err(e.to_string())
                        })?;
                        let mut slf = bound.borrow_mut();
                        slf.trained = Some(model);
                        slf.is_classif = is_classif;
                    }
                    Ok(obj
                        .downcast_into::<Self>()
                        .map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(e.to_string()))?
                        .unbind())
                }
            }
        )+
    };
}
pub(crate) use add_persistence_methods;
